# 采用toml文件格式
# https://github.com/BurntSushi/toml

# grpc.trongrid.io:50051 主节点 本身是负载均衡的
# https://cn.developers.tron.network/docs/官方公共节点
# grpc.shasta.trongrid.io:50051 测试节点
[client]
nodeTrx="grpc.shasta.trongrid.io:50051" # fullnode 主节点
nodeUrl=[] # fullnode 其他节点
main_addr="TDRPyn57F4riYTJFcHaQbrzgFaGe8HSumL" #主钱包地址
password="1070fcd0-ed20-425d-af1f-6d217d2e4820" #主钱包秘钥加密前的密码 uuid
main_pri="" #主钱包加密私钥
seed=""
seed_pri=""
db_addr="/opt/tron/tron.db"
port="8245"
logLevel="info" # 日志等级默认
count=3 #批量查询交易记录个数
feelimit=5000000 # 每次转账trc20合约燃烧的能量 单位sun 默认5trx
perfee=5 # 每次归集每个合约需要手续费消耗
minfee=5 # 每个地址至少保留多少trx手续费
is_multi = false

# 合约配置
[[contract]]
name="USDT"  # 暂时没有用到
type="trc20" # 合约类型
contract="TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t" # trc20 合约地址
issuer="THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC" # 发行者地址 暂时没有用到
port="8246" # 监听端口
min_amount=50 # 最小归集数量

[[contract]]
name="BTT"
type="trc10" # 合约类型
contract="1002000" # 合约配置 trc10 合约ID assertname
issuer="TF5Bn4cJCT6GVeUgyCN4rBhDg42KBrpAjg" # 发行者地址 暂时没有用到
port="8247" # 监听端口
min_amount=100 # 最小归集数量

[collection]
time_interval_min=60 # 归集检测间隔  单位 分
min_amount=100 # trx最小归集钱包余额 单位TRX 后面 6个零 1TRX =10^6SUN

[scantraderecord]
time_interval_sec=15 # 扫描交易记录检测间隔 单位秒
# 扫描交易记录起始位置 如果配置为正数 取最大值开始扫描
# 如果为负数 则取绝对值 从绝对值位置开始扫描，不取最大值开始扫描
min_scan_block = 38605253
goroutine_num=4 # 每次扫描开的协程数量 每个协程扫描能一次扫描100个块 是很快的 tron 3秒更新一次块 完全很快就追上了
